#%RAML 1.0
---

title: Tic Toc Toe Game API
version: 1.0
protocols: [ HTTP ]
baseUri: http://tic.tac.toe/
mediaType: application/json

/game:
  post:
    description: Start a new Game with an empty 3x3 board
    responses:
      201:
        headers:
          Location:
            example: /game/{gameId}
            description: Resource path to the new Game
  /{gameId}/state:
    uriParameters:
      gameId:
        displayName: Game ID
        description: An identifier which uniquely identifies a Game
        type: string
    get:
      description: Use this resource if you want to know the current state of the Game
      responses:
        200:
          body:
            application/json:
              type: !include schemas/game_state.json
              example: !include examples/game_state.json
        404:
          body:
            application/json:
              schema: !include schemas/error.json
              example: !include examples/errors/404_GAME_NOT_FOUND.json

  /{gameId}/board/{symbol}:
    uriParameters:
      gameId:
        displayName: Game ID
        description: An identifier which uniquely identifies a Game
        type: string
      symbol:
        enum: ["x", "o"]
    put:
      description: Use this resource to place the given symbol on the Game board
      body:
        application/json:
          type: !include schemas/player_move.json
          example: !include examples/player_move.json
      responses:
        204:
        400:
          body:
            application/json:
              schema: !include schemas/error.json
              example: !include examples/errors/400_INVALID_LOCATION.json
        403:
          body:
            application/json:
              schema: !include schemas/error.json
              example: !include examples/errors/403_GAME_OVER.json
        404:
          body:
            application/json:
              schema: !include schemas/error.json
              example: !include examples/errors/404_GAME_NOT_FOUND.json
        409:
          body:
            application/json:
              schema: !include schemas/error.json
              example: !include examples/errors/409_OCCUPIED_LOCATION.json
