#%RAML 1.0
---

title: Tic Toc Toe Game API
version: 1.0
protocols: [ HTTP ]
baseUri: http://tic.tac.toe/
mediaType: application/json

/game:
  displayName: Game Resource
  description: Use this resource to start a new Game with empty 3x3 board
  post:
    displayName: Start a Game
    description: Start a new Game with an empty 3x3 board
    responses:
      201:
        headers:
          Location:
            example: /game/{gameId}
            description: Resource path to the new Game
  /{gameId}/state:
    displayName: Game State Resource
    description: Resource which provides the current state of the Game
    uriParameters:
      gameId:
        displayName: Game ID
        description: An identifier which uniquely identifies a Game
        type: string
    get:
      displayName: Get the Game
      description: Get this resource if you want to know the current state of the Game
      responses:
        200:
          body:
            application/json:
              type: !include schemas/game.json
              example: !include examples/game.json
        404:
          body:
            application/json:
              schema: !include schemas/error.json
              example: !include examples/errors/404_GAME_NOT_FOUND.json

  /{gameId}/board/{symbol}:
    displayName: Board Symbol Resource
    description: Use this resource to place the given symbol on the Game board
    uriParameters:
      gameId:
        displayName: Game ID
        description: An identifier which uniquely identifies a Game
        type: string
      symbol:
        displayName: Symbol
        description: Symbol
        enum: ["x", "o"]
    put:
      body:
        application/json:
          type: !include schemas/player_move.json
          example: !include examples/player_move.json
      responses:
        204:
        400:
          body:
            application/json:
              schema: !include schemas/error.json
              example: !include examples/errors/400_INVALID_LOCATION.json
        403:
          body:
            application/json:
              schema: !include schemas/error.json
              example: !include examples/errors/403_GAME_OVER.json
        404:
          body:
            application/json:
              schema: !include schemas/error.json
              example: !include examples/errors/404_GAME_NOT_FOUND.json
        409:
          body:
            application/json:
              schema: !include schemas/error.json
              example: !include examples/errors/409_OCCUPIED_LOCATION.json
